set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER ${ARM_HOME}/bin/arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER ${ARM_HOME}/bin/arm-none-eabi-g++)
